### ISSUE TITLE
Initialize error

### ISSUE THREAD

**Issue by CHLAI0410** [randy3k/homebrew-r#52]
Initialize error pops up after successful login
tried all ways, not really saw any error

Except when verify installation

> 07 Jun 2018 01:49:31 [rserver] ERROR system error 13 (Permission denied); OCCURRED AT: rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(SocketAcceptorService<boost::asio::ip::tcp> &, const std::string &, const std::string &) /tmp/rstudio-server-20180528-5836-1y8qgav/rstudio-1.1.453/src/cpp/core/include/core/http/TcpIpSocketUtils.hpp:103; LOGGED FROM: int main(int, char *const *) /tmp/rstudio-server-20180528-5836-1y8qgav/rstudio-1.1.453/src/cpp/server/ServerMain.cpp:445

Is the r-x11 necessary? I  am using R installed for studio desktop (R 3.5.0)

**Comment by randy3k** [comment]
Did you follow the steps in the [README](https://github.com/randy3k/homebrew-r#installing-rstudio-server)?

**Comment by randy3k** [comment]
For some reason, I got the same result when using the bottle. Please build it from the source and try again

```
brew install rstudio-server --build-from-source
```

**Comment by randy3k** [comment]
I found a fix for my case. It was because the R binary was not correctly linked.
```
brew link r
```

If you are using the bottle, you have to at least link the homebrew `r` (not `r-x11`). You could switch to another R in the RStudio interface though.

**Comment by CHLAI0410** [comment]
I tried your suggestion of using `brew install rstudio-server --without-r` and finally it works. Thanks.
